import moment from 'moment';

export const formatDateTime = dateString => {
  const date = moment(dateString);

  if (date.isSame(moment(), 'day')) {
    // If it's today → show only time
    return date.format('hh:mm A');
  } else {
    // If it's not today → show date + time
    return date.format('D MMMM hh:mm A');
  }
};

export const GetName = username => {
  const data =
    username != null &&
    username
      .split(' ')
      .map(word => word.charAt(0).toUpperCase())
      .join('');
  return data;
};

export const Mincount = [
  {label: 'Item 1', value: '1'},
  {label: 'Item 2', value: '2'},
  {label: 'Item 3', value: '3'},
  {label: 'Item 4', value: '4'},
  {label: 'Item 5', value: '5'},
  {label: 'Item 6', value: '6'},
  {label: 'Item 7', value: '7'},
  {label: 'Item 8', value: '8'},
  {label: 'Item 9', value: '9'},
  {label: 'Item 10', value: '10'},
  {label: 'Item 11', value: '11'},
  {label: 'Item 12', value: '12'},
  {label: 'Item 13', value: '13'},
  {label: 'Item 14', value: '14'},
  {label: 'Item 15', value: '15'},
  {label: 'Item 16', value: '16'},
  {label: 'Item 17', value: '17'},
  {label: 'Item 18', value: '18'},
  {label: 'Item 19', value: '19'},
  {label: 'Item 20', value: '20'},
  {label: 'Item 21', value: '21'},
  {label: 'Item 22', value: '22'},
  {label: 'Item 23', value: '23'},
  {label: 'Item 24', value: '24'},
  {label: 'Item 25', value: '25'},
  {label: 'Item 26', value: '26'},
  {label: 'Item 27', value: '27'},
  {label: 'Item 28', value: '28'},
  {label: 'Item 29', value: '29'},
  {label: 'Item 30', value: '30'},
  {label: 'Item 31', value: '31'},
  {label: 'Item 32', value: '32'},
  {label: 'Item 33', value: '33'},
  {label: 'Item 34', value: '34'},
  {label: 'Item 35', value: '35'},
  {label: 'Item 36', value: '36'},
  {label: 'Item 37', value: '37'},
  {label: 'Item 38', value: '38'},
  {label: 'Item 39', value: '39'},
  {label: 'Item 40', value: '40'},
  {label: 'Item 41', value: '41'},
  {label: 'Item 42', value: '42'},
  {label: 'Item 43', value: '43'},
  {label: 'Item 44', value: '44'},
  {label: 'Item 45', value: '45'},
  {label: 'Item 46', value: '46'},
  {label: 'Item 47', value: '47'},
  {label: 'Item 48', value: '48'},
  {label: 'Item 49', value: '49'},
  {label: 'Item 50', value: '50'},
  {label: 'Item 51', value: '51'},
  {label: 'Item 52', value: '52'},
  {label: 'Item 53', value: '53'},
  {label: 'Item 54', value: '54'},
  {label: 'Item 55', value: '55'},
  {label: 'Item 56', value: '56'},
  {label: 'Item 57', value: '57'},
  {label: 'Item 58', value: '58'},
  {label: 'Item 59', value: '59'},
  {label: 'Item 60', value: '60'},
  {label: 'Item 61', value: '61'},
  {label: 'Item 62', value: '62'},
  {label: 'Item 63', value: '63'},
  {label: 'Item 64', value: '64'},
  {label: 'Item 65', value: '65'},
  {label: 'Item 66', value: '66'},
  {label: 'Item 67', value: '67'},
  {label: 'Item 68', value: '68'},
  {label: 'Item 69', value: '69'},
  {label: 'Item 70', value: '70'},
  {label: 'Item 71', value: '71'},
  {label: 'Item 72', value: '72'},
  {label: 'Item 73', value: '73'},
  {label: 'Item 74', value: '74'},
  {label: 'Item 75', value: '75'},
  {label: 'Item 76', value: '76'},
  {label: 'Item 77', value: '77'},
  {label: 'Item 78', value: '78'},
  {label: 'Item 79', value: '79'},
  {label: 'Item 80', value: '80'},
  {label: 'Item 81', value: '81'},
  {label: 'Item 82', value: '82'},
  {label: 'Item 83', value: '83'},
  {label: 'Item 84', value: '84'},
  {label: 'Item 85', value: '85'},
  {label: 'Item 86', value: '86'},
  {label: 'Item 87', value: '87'},
  {label: 'Item 88', value: '88'},
  {label: 'Item 89', value: '89'},
  {label: 'Item 90', value: '90'},
  {label: 'Item 91', value: '91'},
  {label: 'Item 92', value: '92'},
  {label: 'Item 93', value: '93'},
  {label: 'Item 94', value: '94'},
  {label: 'Item 95', value: '95'},
  {label: 'Item 96', value: '96'},
  {label: 'Item 97', value: '97'},
  {label: 'Item 98', value: '98'},
  {label: 'Item 99', value: '99'},
  {label: 'Item 100', value: '100'},
];

export const hourCount = [
  {label: 'Item 1', value: '1'},
  {label: 'Item 2', value: '2'},
  {label: 'Item 3', value: '3'},
  {label: 'Item 4', value: '4'},
  {label: 'Item 5', value: '5'},
  {label: 'Item 6', value: '6'},
  {label: 'Item 7', value: '7'},
  {label: 'Item 8', value: '8'},
  {label: 'Item 9', value: '9'},
  {label: 'Item 10', value: '10'},
  {label: 'Item 11', value: '11'},
  {label: 'Item 12', value: '12'},
  {label: 'Item 13', value: '13'},
  {label: 'Item 14', value: '14'},
  {label: 'Item 15', value: '15'},
  {label: 'Item 16', value: '16'},
  {label: 'Item 17', value: '17'},
  {label: 'Item 18', value: '18'},
  {label: 'Item 19', value: '19'},
  {label: 'Item 20', value: '20'},
  {label: 'Item 21', value: '21'},
  {label: 'Item 22', value: '22'},
  {label: 'Item 23', value: '23'},
  {label: 'Item 24', value: '24'},
];
